name: caytrack
description: "Smart Tracking for Ceylon."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # Maps & Location
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  geolocator: ^11.0.1
  permission_handler: ^11.0.1
  geocoding: ^3.0.0

  # Media - stable for web and Flutter 3.x
  image_picker: ^1.1.2

  # Firebase - latest 3.x compatible
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.10


  # Others
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/logo/logo2.png
    - assets/logo/fac.png
    - assets/logo/land.jpg
    - assets/developer/developer_photo.png